name: Docs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  loop:
    name: Sync documents from upstream loop repo
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls

      - name: Checkout test-sync repo
        uses: actions/checkout@v2
        with:
          path: test-sync

      - name: Checkout loop repo
        uses: actions/checkout@v2
        with:
          repository: lightninglabs/loop
          path: loop

      - name: Diff and commit
        run: ./test-sync/scripts/docs_sync.sh docs loop test-sync