name: Docs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  loop:
    name: Sync documents from upstream loop repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test-sync repo
        uses: actions/checkout@v2
        with:
          path: test-sync

      - name: Checkout loop repo
        uses: actions/checkout@v2
        with:
          repository: lightninglabs/loop
          path: loop

      # TODO(carla): do a git diff and clean exit if there is no difference

      - name: ls
        run: ls

      - name: Clear our current loop docs
        run: rm -rf test-sync/docs/loop

      - name: Create loop docs dir
        run: mkdir -p test-sync/docs/loop

      - name: Clear our current loop docs
        run: cp loop/docs/* test-sync/docs/loop/

      - name: Commit loop files
        run: git add . git commit -m "docs sync loop"
