name: Docs - experimental

on:
  # TODO(carla): uncomment this once done with demo
  # schedule:
  # * is a special character in YAML so you have to quote this string
  #- cron:  '*/60 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  sync-docs:
    name: Sync documents from upstream
    runs-on: ubuntu-latest
    strategy:
      # Allow other tests in the matrix to continue if one fails.
      fail-fast: false
      matrix:
        cfg:
          - { repo: lnd, org: lightningnetwork, src: docs, dest: advanced-best-practices }
          - { repo: lightning-terminal, org: lightninglabs, src: docs, dest: intermediate-get-lit }

    steps:
      - name: Checkout test-sync repo
        uses: actions/checkout@v2

      - name: Checkout ${{ matrix.cfg.repo }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.cfg.org }}/${{ matrix.cfg.repo }}
          path: ${{ matrix.cfg.repo }}

      - name: Create branch
        run: ./scripts/branch.sh ${{ matrix.cfg.repo }} ${{ matrix.cfg.src }} ${{ matrix.cfg.dest }}

      # We get the current time so that our branches can have unique names.
      # Otherwise, the pull request action will overwrite itself.
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update documentation
          title: Update ${{ matrix.cfg.repo }} documentation
          body: This PR was created to automatically sync ${{ matrix.cfg.repo }} documentation.
          branch: docs-${{ matrix.cfg.repo }}-${{ steps.current-time.outputs.time }}
          base: master

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"