name: Docs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  loop:
    name: Sync documents from upstream
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - lnd
          - loop
          - pool
        include:
          - repo: lnd
            ORG=lightningnetwork
          - repo: pool
            ORG=lightninglabs
          - repo: loop
            ORG=lightninglabs
    steps:
      - name: ls
        run: ls

      - name: Checkout test-sync repo
        uses: actions/checkout@v2
        with:
          path: test-sync

      - name: Checkout ${{ matrix.repo }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.ORG }}/${{ matrix.repo }}
          path: ${{ matrix.repo }}

      - name: Diff and commit
        run: ./test-sync/scripts/docs_sync.sh docs ${{ matrix.repo }} test-sync