name: Docs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  loop:
    name: Sync documents from upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-sync repo
        uses: actions/checkout@v2
        with:
          path: test-sync

      - name: Checkout lnd repo
        uses: actions/checkout@v2
        with:
          repository: lightningnetwork/lnd
          path: lnd

      - name: Checkout loop repo
        uses: actions/checkout@v2
        with:
          repository: lightninglabs/loop
          path: loop

      - name: Checkout pool repo
        uses: actions/checkout@v2
        with:
          repository: lightninglabs/pool
          path: pool

      - name: Sync lnd
        run: ./test-sync/scripts/docs_sync.sh docs lnd test-sync md

      - name: Sync loop
        run: ./test-sync/scripts/docs_sync.sh docs loop test-sync md

      - name: Sync pool
        run: ./test-sync/scripts/docs_sync.sh docs pool test-sync md

      - name: Commit changes
        run: ./test-sync/scripts/commit.sh test-sync "update documentation"